[package]
name = "multiplication-schonhage-strassen"
version = "0.1.0"
edition = "2024"
authors = ["Stepan Dolgorukov <dolgorukovpro@gmail.com>"]

[[bin]]
name = "muss"
path = "main.rs"

[dependencies]
num-bigint = "0.4.6"
num-traits = "0.2.19"
num-complex = "0.4.6"
